package icons;

import javax.swing.Icon;

import com.intellij.openapi.util.IconLoader;
import consulo.ui.image.Image;
import consulo.ui.migration.SwingImageRef;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class MavenIcons {
  private static SwingImageRef load(String path) {
    return IconLoader.getIcon(path, MavenIcons.class);
  }

  public static final Icon ChildrenProjects = load("/images/childrenProjects.png"); // 12x12
  public static final Image MavenLogo = load("/images/mavenLogo.png"); // 16x16
  public static final Icon MavenPlugin = load("/images/mavenPlugin.png"); // 16x16
  public static final Icon MavenProject = load("/images/mavenProject.png"); // 16x16
  public static final Icon ModulesClosed = load("/images/modulesClosed.png"); // 16x16
  public static final Icon OfflineMode = load("/images/offlineMode.png"); // 16x16
  public static final Icon ParentProject = load("/images/parentProject.png"); // 12x12
  public static final Image Phase = load("/images/phase.png"); // 16x16
  public static final Icon PhasesClosed = load("/images/phasesClosed.png"); // 16x16
  public static final Icon PluginGoal = load("/images/pluginGoal.png"); // 16x16
  public static final Icon ProfilesClosed = load("/images/profilesClosed.png"); // 16x16
  public static final Icon ToolWindowMaven = load("/images/toolWindowMaven.png"); // 13x13
  public static final Icon UpdateFolders = load("/images/updateFolders.png"); // 16x16
  public static final Icon Console = load("/images/ql_console.png"); // 16x16
}
